### PR TITLE
field name error

### PR DESCRIPTION
**Pull request by khejing**
please see: https://github.com/squeeks/glossy/blob/master/lib/glossy/produce.js#L99

### CODE REVIEW

**Comment by santigimeno** [comment]
@khejing thanks for the contribution! Can you add a test for this? Thanks!

**Comment by khejing** [comment]
@santigimeno Test has been added and passed, can you take a look at it?

**Comment by santigimeno** [comment]
Landed with commit message reworded in https://github.com/winstonjs/winston-syslog/commit/954fececa5608ebac73ee8d40a20053d1bea758c and https://github.com/winstonjs/winston-syslog/commit/a5e265fb182f98e43b78112f48c97bc888bf83d3.

Published in `1.2.2`.

Thanks!!

**Comment by santigimeno** [comment]
Correction. It has been tagged as `1.2.2`. It needs to be published though (I have no permissions for that). Pinging @indexzero

**Pull request closed without merging**
