### PR TITLE
Always emit closed event after removing transport

### PR DESCRIPTION
**Pull request by santigimeno**
This wasn't working when the transport hadn't been used.
Update tests.

### CODE REVIEW

**Comment by santigimeno** [comment]
I've added my commit over the commit from the PR: https://github.com/winstonjs/winston-syslog/pull/45

**Comment by santigimeno** [comment]
Ugh, I've just noticed https://github.com/winstonjs/winston-syslog/pull/51 does essentially the same as this PR except for the test. I've tried to incorporate the commit in that PR into mine, but the style checks fail. I think the best option would be to wait for https://github.com/winstonjs/winston-syslog/pull/51 to land and then I can adapt mine.

**Comment by indexzero** [comment]
@santigimeno do you have interest in being a maintainer of `winston-syslog`?

**Comment by santigimeno** [comment]
@indexzero yeah, I can help with that.

**Comment by indexzero** [comment]
Cool. You should have in invite to the organization in your inbox or you can accept it here: https://github.com/winstonjs.

You have pull/push to git. Just ping me when you're ready to do an `npm` release and I'll publish it. After the first few of those I'll add you to `npm` as well. Thanks for contributing!

**Comment by santigimeno** [comment]
Thanks!

**Comment by santigimeno** [comment]
Merged: https://github.com/winstonjs/winston-syslog/commit/e1e3d5070e85b5f82abbc7e9f1b7e90ba4bac135, https://github.com/winstonjs/winston-syslog/commit/9655302c2860238f9418feeb6cfca105a6cd7963, https://github.com/winstonjs/winston-syslog/commit/e0bbe985f1223ed116b50554075012d471ff2a0b

**Pull request closed without merging**
