### PR TITLE
unix-connect: a couple of fixes

### PR DESCRIPTION
**Pull request by santigimeno**
- Call callback on connect error.
- Flush queue once connected.

### CODE REVIEW

**Comment by indexzero** [comment]
Is there a test that illustrates what this fixes?

**Comment by santigimeno** [comment]
@indexzero Both changes fix the current behaviour in the case rsyslog daemon is down. If we start logging and can't connect to `/dev/log` the connect callback was never called. If sometime later, rsyslog daemon recovered we would like to recover this missing messages first, thus the `flushQueue` call.
I'll try to come up with a decent test case

**Comment by santigimeno** [comment]
@indexzero added a couple of new commits:

- call `log` callback from the `connect` callback.
- unix-connect tests

**Comment by indexzero** [comment]
Test === winning

**Pull request merged**
