### PR TITLE
Add support for configurable end-of-line character to be added per me…

### PR DESCRIPTION
**Pull request by brakon**
Fixes issue: 
https://github.com/winstonjs/winston-syslog/issues/47 TCP messages are being written to a single line in syslog

### CODE REVIEW

**Comment by arabold** [comment]
This works pretty well and enables you to use syslog protocol for shipping logs to Logstash and similar processors. Simple and straight forward... 

+1 for merging this

**Comment by maaaikoool** [comment]
+1

**Comment by indexzero** [comment]
Thanks for your contribution!

**Comment by capaj** [comment]
@arabold how does it enable you to use winston-syslog with Logstash? Do you just put any random character at the end of each log? Like `' '` a space? Or is there a better character you recommend to use with logstash?

**Comment by arabold** [comment]
@capaj This task was from last year and we've moved away from Logstash in the meantime. So I'm not of much help anymore. IIRC the linked pull request solved the issue by simply appending a new line character at the end of each TCP message if enabled in `options`. That's it. So if you haven't done so, just set the `options.eol` flag and it should work.

**Pull request merged**
