### PR TITLE
Make "unix-dgram" optional dependancy, add queue limit and fix TCP protocol

### PR DESCRIPTION
**Pull request by sergeyksv**
Hi there. Earlier I already submitted unix-dgram fix. Somebody answered that you will do something better in #22, but finally it became something different and issues is exist. Optional dependency is absolutely safe thing. System that will have it will work, other (solaris) will not fail.
Next to that we was need to use TCP protocol and it appears to be not working. There is no message delimiters (LF). Additionally to avoid memory overuse we add limit for message queue. Hop you find it useful.

### CODE REVIEW

**Comment by markstos** [comment]
The queue limit is important here. Without it, queue growth would be unlimited under the right conditions, causing eventual memory exhaustion.

**Comment by santigimeno** [comment]
These changes look good. Could they be incorporated after rebasing to current master?

**Comment by indexzero** [comment]
@santigimeno sure. Do you want to add them to your PR, #54?

**Comment by cjbarth** [comment]
This PR is quite old and seems that it might not apply to the current version. Can it be rebased or, if it is no longer relevant, closed @sergeyksv ?

**Pull request closed without merging**
