### PR TITLE
TLS connection support (close #66)

### LINKED ISSUE #66: TLS connection support
Do you have any plans to add support for TLS connection to remote syslog servers?

We need this for a high compliance environment where all logging is secured.

### PR DESCRIPTION
**Pull request by pepakriz**

### CODE REVIEW

**Comment by billcrook** [comment]
+1

**Comment by smferguson** [comment]
+1

**Comment by DABH** [comment]
This seems to be a draft, I’m happy to give a proper review when it’s marked as ready.  Anyone who wants to help move this PR forward is encouraged to help :)

On a quick read this seems not too far off...

**Comment by DABH** [comment]
Specifically one comment is it would be good to have some minimal test for this new type

**Comment by pepakriz** [comment]
I would like to finalize this PR, but I'm not able to run tests. Master branch is failing for many reasons (eslint, vows). 

Please enable automatic PR pipelines and fix the master branch at first. Thank you!

**Comment by DABH** [comment]
@pepakriz done :sunglasses: merge master into your pr

**Comment by Daniel231** [comment]
Any progress with the issue? can I help with the development @pepakriz?

**Comment by DABH** [comment]
@Daniel231 if you make a new PR that has this stuff but based off the latest `master` (so there are no conflicts) then I think this could be mergeable.  Or if @pepakriz merges master into this branch we can merge this PR.  Either way

**Comment by pepakriz** [comment]
Hi guys. I've rebased it, but it should be tested. I don't have time for it, because I'm satisfied with winston-log2gelf library.

**Pull request merged**
